# Generated by Django 4.2.4 on 2024-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='input_format',
            field=models.CharField(choices=[('A', 'Alpino'), ('C', 'CHAT'), ('T', 'plain text'), ('F', 'FoLiA'), ('', 'auto-detect')], max_length=2),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Upload date and time'),
        ),
    ]
