# Generated by Django 4.2.4 on 2024-08-09 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0006_remove_treebank_input_file_and_more'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treebankupload',
            name='id',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='input_dir',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='sentence_tokenized',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='sentences_have_labels',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='word_tokenized',
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='input_file',
            field=models.FileField(upload_to='uploaded_treebanks/'),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='input_format',
            field=models.CharField(choices=[('A', 'Alpino'), ('C', 'CHAT'), ('T', 'plain text'), ('F', 'FoLiA'), ('', 'auto-detect')], max_length=2),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='processed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='treebank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='treebanks.treebank'),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Upload date and time'),
        ),
        migrations.AddConstraint(
            model_name='treebankupload',
            constraint=models.UniqueConstraint(fields=('treebank',), name='treebankupload_uniqueness'),
        ),
    ]
