# Generated by Django 4.2.4 on 2024-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_contact_alter_treebankupload_input_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treebankupload',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
