# Generated by Django 4.2.4 on 2024-07-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_treebankupload_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='treebankupload',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='treebankupload',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
