# Generated by Django 4.2.4 on 2024-07-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0006_remove_treebank_input_file_and_more'),
        ('upload', '0004_delete_contact_treebankupload_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treebankupload',
            name='sentence_tokenized',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='sentences_have_labels',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='word_tokenized',
        ),
        migrations.AddField(
            model_name='treebankupload',
            name='url_more_info',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='input_file',
            field=models.FileField(upload_to='uploaded_treebanks/'),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='processed',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='treebank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treebanks.treebank'),
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='upload_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Upload date and time'),
        ),
        migrations.AddConstraint(
            model_name='treebankupload',
            constraint=models.UniqueConstraint(fields=('name',), name='treebankupload_uniqueness'),
        ),
    ]
