# Generated by Django 4.2.4 on 2024-08-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0007_alter_treebank_description_and_more'),
        ('upload', '0005_remove_treebankupload_sentence_tokenized_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treebankupload',
            name='treebankupload_uniqueness',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='id',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='name',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='title',
        ),
        migrations.RemoveField(
            model_name='treebankupload',
            name='url_more_info',
        ),
        migrations.AlterField(
            model_name='treebankupload',
            name='treebank',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='treebanks.treebank'),
        ),
        migrations.AddConstraint(
            model_name='treebankupload',
            constraint=models.UniqueConstraint(fields=('treebank',), name='treebankupload_uniqueness'),
        ),
    ]
