# Generated by Django 4.2.4 on 2024-08-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_remove_treebankupload_treebankupload_uniqueness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treebankupload',
            name='input_dir',
        ),
    ]
