# Generated by Django 4.2.4 on 2024-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0005_remove_component_contains_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treebank',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='upload_timestamp',
        ),
        migrations.AlterField(
            model_name='treebank',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='treebank',
            name='url_more_info',
            field=models.URLField(blank=True, default=''),
        ),
    ]
