# Generated by Django 4.2.4 on 2024-07-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0005_remove_component_contains_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treebank',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='treebank',
            name='upload_timestamp',
        ),
    ]
