# Generated by Django 4.2.4 on 2024-08-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0006_remove_treebank_input_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treebank',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='treebank',
            name='url_more_info',
            field=models.URLField(blank=True, default=''),
        ),
    ]
