# Generated by Django 4.2.4 on 2024-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0006_remove_treebank_input_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treebank',
            name='groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
